# Generated by Django 4.2.5 on 2023-09-09 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('k_a', '0002_question_answered_alter_question_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answered',
            new_name='is_answered',
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='k_a.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
